services:
  user-service:
    build: ./back/user
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/user_db
      - HASH_KEY_JWT=dominaTest
      - HASH_KEY_USER=dominaSecretKey
      - PORT=5000
    depends_on:
      - mongo

  task-service:
    build: ./back/task
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/task_db
      - HASH_KEY_JWT=dominaTest
      - PORT=5001
    depends_on:
      - mongo
  # Servicio de frontend
  frontend:
    build: ./front # Ruta al Dockerfile del frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL_API_SERVICE_TASK=http://localhost:5001/api # URL de la API TASK
      - REACT_APP_BASE_URL_API_SERVICE_USER=http://localhost:5000/api # URL de la API USER

  mongo:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
